exemptAssignees: false
exemptLabels:
  - pinned
  - RFC
  - bug
  - in progress
  - security
exemptMilestones: false
exemptProjects: false
daysUntilClose: 7
daysUntilStale: 60
limitPerRun: 30
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
onlyLabels:
  - weekly-digest
staleLabel: stale
